
### Auth Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "test1234"
}

### Auth access

GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiJ9.YWRtaW4.pwTe9-T-2fy2Vn_ygKTwJePF0mpR8SsMWCHALFtcgoY"

### User

GET http://localhost:3000/users

###

GET http://localhost:3000/users/14

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "login": "manager",
  "password": "test1234",
  "role": "manager"
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "password": "5555"
}

###

DELETE http://localhost:3000/users/4

### Geolocation

GET http://localhost:3000/geolocation

###

GET http://localhost:3000/geolocation/2

###

POST http://localhost:3000/geolocation
Content-Type: application/json

{
  "latitude": "49.978694499999996",
  "longitude": "36.2088506"
}

###

PUT http://localhost:3000/geolocation/2
Content-Type: application/json

{
  "longitude": "37.2088506"
}

###

DELETE http://localhost:3000/geolocation/11
