GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "login": "TEst User12334",
  "password": "1234"
}

###

PUT http://localhost:3000/users/1234

###

DELETE http://localhost:3000/users/1234